repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^.*\.egg-info/
      - id: check-json
      - id: check-toml
      - id: check-case-conflict
      - id: check-docstring-first
      - id: detect-private-key
      - id: check-yaml
      - id: check-ast
      - id: check-added-large-files
      - id: debug-statements
      - id: pretty-format-json
        args: [--autofix, --no-ensure-ascii, --no-sort-keys, --indent=4]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.291
    hooks:
      - id: ruff
        files: '\.py$'
        args: ["--config", "./pyproject.toml"]
