name: run pytest
on:
  pull_request:
    branches:
      - "main"


env:
  # STATIC POETRY CONFIG
  POETRY_VIRTUALENVS_CREATE: "true"
  POETRY_VIRTUALENVS_IN_PROJECT: "true"
  POETRY_NO_INTERACTION: "true"
  POETRY_INSTALLER_PARALLEL: "true"
  POETRY_INSTALLER_MAX_WORKERS: "6"

jobs:
  pytest:
    runs-on:
      - ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup-python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
